"""Light-space transmittance volume for soft volumetric shadows.

STATUS: scaffolding only. This file is committed but NOT YET wired
into SceneRenderer. See memory file
project_slicer_wgpu_shadows_integration.md for the pick-up plan
(what to do next, open challenges, file:line pointers).


A ``ShadowVolume`` owns a 3D R16F texture in world space covering the
union of all Fields' AABBs. Once per "dirty" cycle (light moved, any
field's data/TF/transform changed, scene bounds changed), a compute
shader integrates optical depth from the light source to each texel
across every participating Field; the texel stores ``exp(-tau)`` =
transmittance. During the main ray march, each shaded sample looks
the texture up trilinearly -- giving soft shadow edges at volume
boundaries for free, since the lookup interpolates across
bounded-opacity regions.

The compute shader is generated by concatenating the same per-Field
``sample_field_<kind><slot>`` WGSL functions the fragment shader uses,
so the shadow build is physically consistent with the main ray march
(same TF LUTs, same gradient-opacity modulation, same transforms).

Single directional light for Stage 1. Multi-light / area lights /
temporal accumulation are follow-on stages.
"""

from __future__ import annotations

import numpy as np
import wgpu


_COMPUTE_TEMPLATE = """
struct ShadowUniforms {
    scene_bounds_min: vec4<f32>,   // xyz + padding
    scene_bounds_max: vec4<f32>,
    light_direction: vec4<f32>,    // world-space, normalized, points FROM surface TO light
    step_size: f32,
    max_steps: u32,
    resolution: u32,               // cubic, R
    _pad: u32,
};

@group(0) @binding(0) var<uniform> u_shadow: ShadowUniforms;
@group(0) @binding(1) var t_out: texture_storage_3d<r16float, write>;

// Per-field sampling functions (same WGSL as the fragment shader).
__FIELD_FUNCTIONS__

// Dummy struct/buffer bindings used by field functions. pygfx's fragment
// shader gets u_material / u_stdinfo / u_wobject injected; our compute
// pass binds its own copies below so the field WGSL compiles unchanged.
__FIELD_UNIFORM_BINDINGS__

fn ray_aabb(o: vec3<f32>, d: vec3<f32>,
            bmin: vec3<f32>, bmax: vec3<f32>) -> vec2<f32> {
    let inv_dir = vec3<f32>(1.0) / d;
    let tb = (bmin - o) * inv_dir;
    let tt = (bmax - o) * inv_dir;
    let tmn = min(tt, tb);
    let tmx = max(tt, tb);
    return vec2<f32>(
        max(max(tmn.x, tmn.y), tmn.z),
        min(min(tmx.x, tmx.y), tmx.z),
    );
}

@compute @workgroup_size(8, 8, 8)
fn build_shadow(@builtin(global_invocation_id) id: vec3<u32>) {
    let R = u_shadow.resolution;
    if (id.x >= R || id.y >= R || id.z >= R) { return; }

    let bmin = u_shadow.scene_bounds_min.xyz;
    let bmax = u_shadow.scene_bounds_max.xyz;

    // Texel center in world space.
    let uvw = (vec3<f32>(id) + vec3<f32>(0.5)) / vec3<f32>(f32(R));
    let wp0 = mix(bmin, bmax, uvw);

    // March FROM the texel TOWARD the light. light_direction points
    // from surface to light, so stepping along +light_direction marches
    // toward the light source.
    let dir = normalize(u_shadow.light_direction.xyz);
    let trange = ray_aabb(wp0, dir, bmin, bmax);
    // Exit distance (entering is behind us since we start inside the box).
    let t_exit = max(trange.y, 0.0);
    if (t_exit <= 0.0) {
        textureStore(t_out, vec3<i32>(id), vec4<f32>(1.0, 0.0, 0.0, 0.0));
        return;
    }

    let step = max(u_shadow.step_size, 1e-3);
    var t: f32 = 0.5 * step;   // small offset so we don't re-sample the
                               //  current shaded sample point itself
    var tau: f32 = 0.0;
    var safety: u32 = 0u;

    loop {
        if (t >= t_exit) { break; }
        if (safety >= u_shadow.max_steps) { break; }

        let wp = wp0 + dir * t;

        // Accumulate per-step opacity across all fields. We want the
        // absorption coefficient, not the already-alpha-blended
        // per-pixel opacity. Treat each field's returned opacity as
        // an alpha for `step` distance and convert to optical depth.
        var op_sum: f32 = 0.0;
__FIELD_OPACITY_ACC__

        // Per-step alpha -> optical-depth contribution:
        //     alpha = 1 - exp(-mu * step)
        //   => mu * step = -ln(1 - alpha)
        let alpha = clamp(op_sum, 0.0, 0.999);
        tau = tau + (-log(1.0 - alpha));

        if (tau > 6.0) { break; }   // transmittance < 0.25%, call it zero

        t = t + step;
        safety = safety + 1u;
    }

    let transmittance = exp(-tau);
    textureStore(t_out, vec3<i32>(id), vec4<f32>(transmittance, 0.0, 0.0, 0.0));
}
"""


def _build_field_opacity_block(fields, slot_indices) -> str:
    """Per-field opacity contribution inside the compute march loop.
    Sums every field's own ``sample_field_*`` opacity at ``wp``.
    """
    lines = []
    for field, slot in zip(fields, slot_indices):
        fn = f"sample_field_{field.field_kind}{slot}"
        lines.append("        {")
        lines.append(f"            let s = {fn}(wp, -dir, wp0);")
        lines.append("            if (s.hit) {")
        lines.append("                op_sum = op_sum + s.opacity;")
        lines.append("            }")
        lines.append("        }")
    if not lines:
        lines.append("        // (no fields)")
    return "\n".join(lines)


class ShadowVolume:
    """A world-space 3D transmittance texture + the compute pipeline
    that refills it when the scene lighting/content changes.

    The texture is sized cubic at ``resolution`` (default 256). Format
    is R16F, so 256^3 = 32 MB. For scenes where that's too much, pass
    a smaller resolution; sub-millimeter shadow detail isn't needed
    since we softly interpolate during lookup.

    Caller is responsible for:
      * constructing one per SceneRenderer after fields are bound,
      * calling ``build(...)`` whenever the light/scene state changes,
      * handing ``get_bindings(start_slot)`` to the fragment shader.

    The shadow texture is sampled trilinearly during the fragment's
    Phong step: each per-field ``tf_wgsl`` multiplies its direct-
    lighting terms by ``sample_shadow(wp)``, leaving ambient alone.
    """

    def __init__(self, device, resolution: int = 256):
        self.device = device
        self.resolution = int(resolution)
        self._pipeline = None
        self._bind_group_layout = None

        # Output transmittance texture.
        self.texture = device.create_texture(
            label="slicer_wgpu.ShadowVolume.transmittance",
            size=(self.resolution, self.resolution, self.resolution),
            dimension=wgpu.TextureDimension.d3,
            format=wgpu.TextureFormat.r16float,
            usage=(wgpu.TextureUsage.STORAGE_BINDING
                   | wgpu.TextureUsage.TEXTURE_BINDING),
        )
        self.texture_view = self.texture.create_view()
        self.sampler = device.create_sampler(
            label="slicer_wgpu.ShadowVolume.sampler",
            mag_filter=wgpu.FilterMode.linear,
            min_filter=wgpu.FilterMode.linear,
            address_mode_u=wgpu.AddressMode.clamp_to_edge,
            address_mode_v=wgpu.AddressMode.clamp_to_edge,
            address_mode_w=wgpu.AddressMode.clamp_to_edge,
        )

        # Uniform buffer: matches ShadowUniforms layout in WGSL.
        self._ubuf_size = 4 * 4 * 4 + 4 * 4   # two vec4 + light vec4 + 4 scalars
        self.uniform_buffer = device.create_buffer(
            label="slicer_wgpu.ShadowVolume.uniforms",
            size=64,  # aligned; see _write_uniforms
            usage=wgpu.BufferUsage.UNIFORM | wgpu.BufferUsage.COPY_DST,
        )

        # (shader module + pipeline built lazily by build_pipeline())
        self._shader_module = None

    # -------- Pipeline lifecycle --------

    def build_pipeline(self, field_functions_wgsl: str,
                       field_uniform_bindings_wgsl: str,
                       field_opacity_acc_wgsl: str,
                       extra_bind_group_layout_entries: list,
                       extra_bind_group_entries: list) -> None:
        """Compile the compute shader for a specific field configuration.

        ``field_functions_wgsl`` is the concatenation of each Field's
        ``sampling_wgsl`` + ``tf_wgsl`` (same text the fragment shader
        uses). ``field_uniform_bindings_wgsl`` declares the ``u_material``
        /``u_stdinfo``/``u_wobject`` uniforms and per-field textures/
        samplers the field functions reference. ``field_opacity_acc_wgsl``
        is produced by ``_build_field_opacity_block``.

        ``extra_bind_group_layout_entries`` and ``extra_bind_group_entries``
        describe the additional resources the field functions need
        (volume textures, LUTs, their samplers, the material uniform
        buffer, etc.). Both start at binding slot 2 (slots 0 and 1 are
        reserved for our own uniforms and the output texture).
        """
        wgsl = (_COMPUTE_TEMPLATE
                .replace("__FIELD_FUNCTIONS__", field_functions_wgsl)
                .replace("__FIELD_UNIFORM_BINDINGS__", field_uniform_bindings_wgsl)
                .replace("__FIELD_OPACITY_ACC__", field_opacity_acc_wgsl))

        self._shader_module = self.device.create_shader_module(
            label="slicer_wgpu.ShadowVolume.compute", code=wgsl)

        layout_entries = [
            # (0) u_shadow
            {"binding": 0, "visibility": wgpu.ShaderStage.COMPUTE,
             "buffer": {"type": wgpu.BufferBindingType.uniform}},
            # (1) output 3D storage texture
            {"binding": 1, "visibility": wgpu.ShaderStage.COMPUTE,
             "storage_texture": {
                 "access": wgpu.StorageTextureAccess.write_only,
                 "format": wgpu.TextureFormat.r16float,
                 "view_dimension": wgpu.TextureViewDimension.d3,
             }},
        ] + list(extra_bind_group_layout_entries)

        bgl = self.device.create_bind_group_layout(
            label="slicer_wgpu.ShadowVolume.bgl", entries=layout_entries)
        pipeline_layout = self.device.create_pipeline_layout(
            label="slicer_wgpu.ShadowVolume.pl", bind_group_layouts=[bgl])

        self._pipeline = self.device.create_compute_pipeline(
            label="slicer_wgpu.ShadowVolume.pipeline",
            layout=pipeline_layout,
            compute={"module": self._shader_module, "entry_point": "build_shadow"},
        )
        self._bind_group_layout = bgl
        self._extra_bind_group_entries = list(extra_bind_group_entries)

    # -------- Per-frame build --------

    def _write_uniforms(self, bmin, bmax, light_dir, step_size, max_steps):
        # Pack ShadowUniforms into 64 bytes, matching WGSL layout.
        data = np.zeros(16, dtype=np.float32)
        data[0:3] = np.asarray(bmin, dtype=np.float32)
        data[4:7] = np.asarray(bmax, dtype=np.float32)
        ld = np.asarray(light_dir, dtype=np.float32)
        ld = ld / max(float(np.linalg.norm(ld)), 1e-6)
        data[8:11] = ld
        data[12] = float(step_size)
        # ints share the last vec4 slot
        ints = np.zeros(4, dtype=np.uint32)
        ints[0] = int(max_steps)
        ints[1] = int(self.resolution)
        # Overlay ints bytes onto data[13:16]
        raw = bytearray(data.tobytes())
        raw[13 * 4:13 * 4 + 4 * 4] = ints.tobytes()
        self.device.queue.write_buffer(self.uniform_buffer, 0, bytes(raw))

    def build(self, bmin, bmax, light_dir,
              step_size: float = 1.0, max_steps: int = 2048) -> None:
        """Dispatch the compute shader to refresh the transmittance
        texture. ``light_direction`` points FROM surface TO light
        (i.e. the vector you'd use for an NdotL term)."""
        if self._pipeline is None:
            raise RuntimeError("ShadowVolume.build called before build_pipeline")

        self._write_uniforms(bmin, bmax, light_dir, step_size, max_steps)

        entries = [
            {"binding": 0, "resource": {
                "buffer": self.uniform_buffer, "offset": 0,
                "size": self.uniform_buffer.size}},
            {"binding": 1, "resource": self.texture_view},
        ] + self._extra_bind_group_entries

        bind_group = self.device.create_bind_group(
            label="slicer_wgpu.ShadowVolume.bg",
            layout=self._bind_group_layout, entries=entries)

        encoder = self.device.create_command_encoder(
            label="slicer_wgpu.ShadowVolume.encoder")
        cpass = encoder.begin_compute_pass(
            label="slicer_wgpu.ShadowVolume.pass")
        cpass.set_pipeline(self._pipeline)
        cpass.set_bind_group(0, bind_group, [], 0, 0)
        wg = 8
        groups = (self.resolution + wg - 1) // wg
        cpass.dispatch_workgroups(groups, groups, groups)
        cpass.end()
        self.device.queue.submit([encoder.finish()])
